#=================================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK
#=================================================

name: Build K2

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '**/build-k2.yml'

jobs:
  upload:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Cache restore
      id: cache-lede
      uses: actions/cache@v1
      with:
        path: cache
        key: ${{ runner.os }}-k2-build
    
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
    - name: Push Result
      run : |
        DISTRIB_REVISION=`cat cache/VERSION`
        [[ -d release ]] || mkdir release
        cd release && [[ -d k2 ]] || mkdir k2
        cd k2  && [[ -d $DISTRIB_REVISION ]] || mkdir $DISTRIB_REVISION
        cd ../../
        cp -rf ./cache/bin/* ./release/k2/$DISTRIB_REVISION/
        git config --local user.email "yuwenzhen@qq.com"
        git config --local user.name "RexYu"
        git pull
        echo step pull end
        git add release
        echo add  end
        cd release
        echo release  end
        git commit -m 'commit k2 '$DISTRIB_REVISION 
        echo commit  end
        git push
