#=====================================
#   Description: Build G-DOCK FROM LEAN'S LEDE
#   Author: JK     
#=================================================

name: Build G-DOCK-C

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
    paths:
      - '**/c.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
 
    steps:
    - name: Checkout
      uses: actions/checkout@master

     
    - name: Clone dl
      run: |
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/rexyu/dl
     
        
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede lede   
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: K2
        path: ./lede/scripts
  
    - name: Checkout2
      uses: actions/checkout@v2
      with:
        path: my-tools
    - run: pwd
      
    - name: Push Result
      run : |
        DISTRIB_REVISION=`grep 'DISTRIB_REVISION=' ./lede/package/lean/default-settings/files/zzz-default-settings  | awk -v head="DISTRIB_REVISION='" -v tail="'\"" '{print substr($0, index($0,head)+length(head),index($0,tail)-index($0,head)-length(head))}'`
        [[ -d release ]] || mkdir release
        cd release && [[ -d k2 ]] || mkdir k2
        cd k2  && [[ -d $DISTRIB_REVISION ]] || mkdir $DISTRIB_REVISION
        cd ../../
        cp -rf ./lede/scripts/* release/k2/$DISTRIB_REVISION/
        git config --local user.email "yuwenzhen@qq.com"
        git config --local user.name "RexYu"
        echo $(ls -l | awk '/^d/{print $NF}')
        git pull
        git add release 2>&1
        cd release
        git commit -m 'commit k2 '$DISTRIB_REVISION 
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
